steps:
  - label: ":docker: Build and Publish Multi-arch Image"
    plugins:
      - docker#v5.3.0:
          image: "docker:20.10"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker buildx create --name multiarch-builder --use
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64,linux/arm64 --push
        --tag "abhay900/test1-arm64:${BUILDKITE_BUILD_NUMBER}"
        --file ./Dockerfile .
    agents:
      - "queue=arm64"
  
  - wait
  
  - label: ":test_tube: Verify ARM64 Build"
    commands:
      - docker run --rm "abhay900/test1-arm64:${BUILDKITE_BUILD_NUMBER}" | grep "arm64"
    agents:
      - "queue=arm64"
    depends_on:
      - "Build and Publish Multi-arch Image"
